#!/bin/sh
OUTPUT_STRING='"%(title)s.%(ext)s"'
FILENAME=$( yt-dlp --get-filename -o "%(title)s" $1 )
echo "Datei $FILENAME"
yt-dlp -o $OUTPUT_STRING -S res,ext:mp4:m4a --recode mp4 --no-playlist $1
if [ -f "${FILENAME}.mp4" ]
then
  open "${FILENAME}.mp4"
fi

